// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC29LEtd_uMcmyeqQVgd41buRJfkT3Jzcw',
    appId: '1:912589126319:android:dc849b10e29b80b66df25a',
    messagingSenderId: '912589126319',
    projectId: 'fargot-app',
    storageBucket: 'fargot-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIlwE-nEqEPYN7WrfYT5_tqEMIGc8HoxI',
    appId: '1:912589126319:ios:46785c2f80e6d0e16df25a',
    messagingSenderId: '912589126319',
    projectId: 'fargot-app',
    storageBucket: 'fargot-app.appspot.com',
    iosClientId: '912589126319-de1dens4oi12aqlhl1nemqb5cmo9eu59.apps.googleusercontent.com',
    iosBundleId: 'com.example.fargotPassword',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIlwE-nEqEPYN7WrfYT5_tqEMIGc8HoxI',
    appId: '1:912589126319:ios:46785c2f80e6d0e16df25a',
    messagingSenderId: '912589126319',
    projectId: 'fargot-app',
    storageBucket: 'fargot-app.appspot.com',
    iosClientId: '912589126319-de1dens4oi12aqlhl1nemqb5cmo9eu59.apps.googleusercontent.com',
    iosBundleId: 'com.example.fargotPassword',
  );
}
